version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/projects/nyar-number"
    schedule:
      interval: "weekly"
    target-branch: "dev"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "daily"
