[package]
name = "nyar-number"
version = "0.2.5"
authors = ["Aster <192607617@qq.com>"]
description = "Shard types for valkyrie language"
repository = "https://github.com/nyar-vm/nyar-prime"
documentation = "https://docs.rs/nyar-number"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2021"

[dependencies]
shredder = "0.2.0"
num = "0.4.1"
serde = { version = "1.0.188", optional = true }
rand = { version = "0.8.5", optional = true }

[dev-dependencies]

[features]
default = []
serde = ["dep:serde", "num/serde"]
rand = ["dep:rand", "num/rand"]